# Generated by Django 3.0.6 on 2021-09-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20210920_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('like', models.BooleanField(db_column='Like', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletedAt', null=True)),
                ('post_id', models.ForeignKey(db_column='PostId', on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
                ('user_id', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserActivity',
                'ordering': ('created_at',),
                'managed': True,
            },
        ),
    ]
